# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88039fd57eb81dc9d4a851deaf7d2d6df37f284ff9ee509e15f224e25c4c23cf069bafdfdaea0e527314d126663bdf223d029cdb90b76427b35de5bbe1c265ee

test:
  secret_key_base: 78d3c358100bb8e9f43667b2aa895587b92c14ed4c5dd2be6f036d54d1d39c54cd655dda4e1f0a555310b1cddcd3506519e0875da909e75e9eb1fccea5e8777e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
